version: '2'
services:
    openclinica-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/OpenClinica/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=OpenClinica
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
